version: '2'
services:
  fineract-cn-cassandra:
    image: 'cassandra:latest'
    volumes:
      - ~/volumes/fineract-cn/cassandra/:/var/lib/cassandra/
    environment:
      - CASSANDRA_DC=datacenter1
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
