version: '2'
services:
  fineract-cn-mariadb:
    image: mariadb:10.4
    volumes:
      - ~/volumes/fineract-cn/mariadb/:/var/lib/mysql/
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=seshat
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
