version: '2'
services:
  fineract-cn-provision:
    image: fineract-cn-provision
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
    ports:
      - 8080:8080
  fineract-cn-cassandra:
    extends:
      file: cassandra.yml
      service: fineract-cn-cassandra
  fineract-cn-mariadb:
    extends:
      file: mariadb.yml
      service: fineract-cn-mariadb
