version: '3'
services:
  fineract-cn-cassandra:
    extends:
      file: cassandra.yml
      service: fineract-cn-cassandra

  fineract-cn-mariadb:
    extends:
      file: mariadb.yml
      service: fineract-cn-mariadb

  fineract-cn-activemq:
    extends:
      file: activemq.yml
      service: fineract-cn-activemq

  fineract-cn-eureka:
    extends:
      file: eureka.yml
      service: fineract-cn-eureka

  fineract-cn-identity:
    image: fineract-cn-identity
    environment:
      - JAVA_OPTIONS=-Xmx512m -Xms256m
      - CASSANDRA_CONTACTPOINTS=127.0.0.1:9042
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PWD=password
      - CASSANDRA_KEYSPACE=seshat
      - CASSANDRA_CL=ONE
      - CASSANDRA_CLUSTERNAME=datacenter1
        # MariaDB Connection Settings
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=mysql
        # ActiveMQ Settings
      - MQ_URL='tcp://localhost:61616'
      - MQ_USER=admin
      - MQ_PASS=admin
    ports:
      - 2021:8081
    depends_on:
      - fineract-cn-eureka
      - fineract-cn-mariadb
      - fineract-cn-activemq
      - fineract-cn-cassandra

  fineract-cn-office:
    image: fineract-cn-office
    environment:
      - JAVA_OPTIONS=-Xmx512m -Xms256m
      - CASSANDRA_CONTACTPOINTS=127.0.0.1:9042
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PWD=password
      - CASSANDRA_KEYSPACE=seshat
      - CASSANDRA_CL=ONE
      - CASSANDRA_CLUSTERNAME=datacenter1
      # MariaDB Connection Settings
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=mysql
      # ActiveMQ Settings
      - MQ_URL='tcp://localhost:61616'
      - MQ_USER=admin
      - MQ_PASS=admin
    ports:
      - 2022:8080
    depends_on:
      - fineract-cn-eureka
      - fineract-cn-mariadb
      - fineract-cn-activemq
      - fineract-cn-cassandra